# Hardcoded Currency Data
# Using a hardcoded dictionary for currency details to avoid an unnecessary API call.
CURRENCY_DATA = {
    "USD": {"symbol": "$", "name": "US Dollar", "symbol_native": "$", "order_number": 1},
    "MXN": {"symbol": "MX$", "name": "Mexican Peso", "symbol_native": "$", "order_number": 2},
    "BRL": {"symbol": "R$", "name": "Brazilian Real", "symbol_native": "R$", "order_number": 3},
    "AUD": {"symbol": "AU$", "name": "Australian Dollar", "symbol_native": "$", "order_number": 4},
    "BGN": {"symbol": "BGN", "name": "Bulgarian Lev", "symbol_native": "лв.", "order_number": 5},
    "CAD": {"symbol": "CA$", "name": "Canadian Dollar", "symbol_native": "$", "order_number": 6},
    "CHF": {"symbol": "CHF", "name": "Swiss Franc", "symbol_native": "CHF", "order_number": 7},
    "CNY": {"symbol": "CN¥", "name": "Chinese Yuan", "symbol_native": "CN¥", "order_number": 8},
    "CZK": {"symbol": "Kč", "name": "Czech Republic Koruna", "symbol_native": "Kč", "order_number": 9},
    "DKK": {"symbol": "Dkr", "name": "Danish Krone", "symbol_native": "kr", "order_number": 10},
    "EUR": {"symbol": "€", "name": "Euro", "symbol_native": "€", "order_number": 11},
    "GBP": {"symbol": "£", "name": "British Pound Sterling", "symbol_native": "£", "order_number": 12},
    "HKD": {"symbol": "HK$", "name": "Hong Kong Dollar", "symbol_native": "$", "order_number": 13},
    "HRK": {"symbol": "kn", "name": "Croatian Kuna", "symbol_native": "kn", "order_number": 14},
    "HUF": {"symbol": "Ft", "name": "Hungarian Forint", "symbol_native": "Ft", "order_number": 15},
    "IDR": {"symbol": "Rp", "name": "Indonesian Rupiah", "symbol_native": "Rp", "order_number": 16},
    "ILS": {"symbol": "₪", "name": "Israeli New Sheqel", "symbol_native": "₪", "order_number": 17},
    "INR": {"symbol": "Rs", "name": "Indian Rupee", "symbol_native": "টকা", "order_number": 18},
    "ISK": {"symbol": "Ikr", "name": "Icelandic Króna", "symbol_native": "kr", "order_number": 19},
    "JPY": {"symbol": "¥", "name": "Japanese Yen", "symbol_native": "￥", "order_number": 20},
    "KRW": {"symbol": "₩", "name": "South Korean Won", "symbol_native": "₩", "order_number": 21},
    "MYR": {"symbol": "RM", "name": "Malaysian Ringgit", "symbol_native": "RM", "order_number": 22},
    "NOK": {"symbol": "Nkr", "name": "Norwegian Krone", "symbol_native": "kr", "order_number": 23},
    "NZD": {"symbol": "NZ$", "name": "New Zealand Dollar", "symbol_native": "$", "order_number": 24},
    "PHP": {"symbol": "₱", "name": "Philippine Peso", "symbol_native": "₱", "order_number": 25},
    "PLN": {"symbol": "zł", "name": "Polish Zloty", "symbol_native": "zł", "order_number": 26},
    "RON": {"symbol": "RON", "name": "Romanian Leu", "symbol_native": "RON", "order_number": 27},
    "RUB": {"symbol": "RUB", "name": "Russian Ruble", "symbol_native": "руб.", "order_number": 28},
    "SEK": {"symbol": "Skr", "name": "Swedish Krona", "symbol_native": "kr", "order_number": 29},
    "SGD": {"symbol": "S$", "name": "Singapore Dollar", "symbol_native": "$", "order_number": 30},
    "THB": {"symbol": "฿", "name": "Thai Baht", "symbol_native": "฿", "order_number": 31},
    "TRY": {"symbol": "TL", "name": "Turkish Lira", "symbol_native": "₺", "order_number": 32},
    "ZAR": {"symbol": "R", "name": "South African Rand", "symbol_native": "R", "order_number": 33}
}