# Hardcoded Currency Data
# Using a hardcoded dictionary for currency details to avoid an unnecessary API call.
CURRENCY_DATA = {
    "EUR": {"symbol": "€", "name": "Euro", "symbol_native": "€"},
    "USD": {"symbol": "$", "name": "US Dollar", "symbol_native": "$"},
    "JPY": {"symbol": "¥", "name": "Japanese Yen", "symbol_native": "￥"},
    "BGN": {"symbol": "BGN", "name": "Bulgarian Lev", "symbol_native": "лв."},
    "CZK": {"symbol": "Kč", "name": "Czech Republic Koruna", "symbol_native": "Kč"},
    "DKK": {"symbol": "Dkr", "name": "Danish Krone", "symbol_native": "kr"},
    "GBP": {"symbol": "£", "name": "British Pound Sterling", "symbol_native": "£"},
    "HUF": {"symbol": "Ft", "name": "Hungarian Forint", "symbol_native": "Ft"},
    "PLN": {"symbol": "zł", "name": "Polish Zloty", "symbol_native": "zł"},
    "RON": {"symbol": "RON", "name": "Romanian Leu", "symbol_native": "RON"},
    "SEK": {"symbol": "Skr", "name": "Swedish Krona", "symbol_native": "kr"},
    "CHF": {"symbol": "CHF", "name": "Swiss Franc", "symbol_native": "CHF"},
    "ISK": {"symbol": "Ikr", "name": "Icelandic Króna", "symbol_native": "kr"},
    "NOK": {"symbol": "Nkr", "name": "Norwegian Krone", "symbol_native": "kr"},
    "HRK": {"symbol": "kn", "name": "Croatian Kuna", "symbol_native": "kn"},
    "RUB": {"symbol": "RUB", "name": "Russian Ruble", "symbol_native": "руб."},
    "TRY": {"symbol": "TL", "name": "Turkish Lira", "symbol_native": "₺"},
    "AUD": {"symbol": "AU$", "name": "Australian Dollar", "symbol_native": "$"},
    "BRL": {"symbol": "R$", "name": "Brazilian Real", "symbol_native": "R$"},
    "CAD": {"symbol": "CA$", "name": "Canadian Dollar", "symbol_native": "$"},
    "CNY": {"symbol": "CN¥", "name": "Chinese Yuan", "symbol_native": "CN¥"},
    "HKD": {"symbol": "HK$", "name": "Hong Kong Dollar", "symbol_native": "$"},
    "IDR": {"symbol": "Rp", "name": "Indonesian Rupiah", "symbol_native": "Rp"},
    "ILS": {"symbol": "₪", "name": "Israeli New Sheqel", "symbol_native": "₪"},
    "INR": {"symbol": "Rs", "name": "Indian Rupee", "symbol_native": "টকা"},
    "KRW": {"symbol": "₩", "name": "South Korean Won", "symbol_native": "₩"},
    "MXN": {"symbol": "MX$", "name": "Mexican Peso", "symbol_native": "$"},
    "MYR": {"symbol": "RM", "name": "Malaysian Ringgit", "symbol_native": "RM"},
    "NZD": {"symbol": "NZ$", "name": "New Zealand Dollar", "symbol_native": "$"},
    "PHP": {"symbol": "₱", "name": "Philippine Peso", "symbol_native": "₱"},
    "SGD": {"symbol": "S$", "name": "Singapore Dollar", "symbol_native": "$"},
    "THB": {"symbol": "฿", "name": "Thai Baht", "symbol_native": "฿"},
    "ZAR": {"symbol": "R", "name": "South African Rand", "symbol_native": "R"}
}